type Category =
  | "Condiments"
  | "Drinks"
  | "Fruit"
  | "Gluten Free Cereals & Grain"
  | "Meat & Alternatives"
  | "Milk Alternatives"
  | "Milk Products"
  | "Nuts, Seeds, & Legumes"
  | "Snack Foods & Confectionery"
  | "Sweeteners"
  | "Vegetables";

export interface Item {
  avoid: boolean;
  category: Category;
  measurement: string;
  name: string;
  notes: string;
}

export const data: Item[] = [
  {
    name: "Alfalfa",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Artichoke Hearts",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Aubergine",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Bamboo Shoots",
    category: "Vegetables",
    avoid: false,
    measurement: "½ cup",
    notes: "",
  },
  {
    name: "Bean Sprouts",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Beetroot",
    category: "Vegetables",
    avoid: false,
    measurement: "2 slices",
    notes: "",
  },
  {
    name: "Black Fungi Mushroooms",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Bok Choy",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Broccoli",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Brussel Sprouts",
    category: "Vegetables",
    avoid: false,
    measurement: "2 to 3",
    notes: "",
  },
  {
    name: "Canned Mushroooms",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Carrot",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Celeriac",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Celery",
    category: "Vegetables",
    avoid: false,
    measurement: "¼ cup",
    notes: "",
  },
  {
    name: "Champignon",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Chinese Cabbage",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Choko",
    category: "Vegetables",
    avoid: false,
    measurement: "½ cup",
    notes: "",
  },
  {
    name: "Choy Sum",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Corn",
    category: "Vegetables",
    avoid: false,
    measurement: "Up to ½ cob",
    notes: "",
  },
  {
    name: "Courgette",
    category: "Vegetables",
    avoid: false,
    measurement: "< ½ cup",
    notes: "",
  },
  {
    name: "Cucumber",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Edamame",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Eggplant",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Fennel Bulb & Leaves",
    category: "Vegetables",
    avoid: false,
    measurement: "½ cup",
    notes: "",
  },
  {
    name: "Gai Lan",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Galangal",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Ginger",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Green Beans",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Green Cabbage",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Green Capsicum",
    category: "Vegetables",
    avoid: false,
    measurement: "½ cup",
    notes: "",
  },
  {
    name: "Green Chilli",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Japanese  Pumpkin",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Kabocha Squash Pumpkin",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Kale",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Kent Pumpkin",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Leek",
    category: "Vegetables",
    avoid: false,
    measurement: "Green part only",
    notes: "",
  },
  {
    name: "Lettuce (all types)",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Nori Seaweed",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Okra",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Oyster Mushroooms",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Parsnip",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Potato",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Radish",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Red Cabbage",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Red Capsicum",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Red Chilli",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Red Sauerkraut",
    category: "Vegetables",
    avoid: false,
    measurement: "3 tablespoons",
    notes: "",
  },
  {
    name: "Shimeji Mushroooms",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Silverbeet",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Snow Peas",
    category: "Vegetables",
    avoid: false,
    measurement: "<= 5 pods",
    notes: "",
  },
  {
    name: "Spinach",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Spring Onion",
    category: "Vegetables",
    avoid: false,
    measurement: "Green only",
    notes: "",
  },
  {
    name: "Squash",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Sweet Potato",
    category: "Vegetables",
    avoid: false,
    measurement: "Up to ½ cup",
    notes: "",
  },
  {
    name: "Taro",
    category: "Vegetables",
    avoid: false,
    measurement: "Up to ½ cup",
    notes: "",
  },
  {
    name: "Tomatoes",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Turnip",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Water Chestnut",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "White Sauerkraut",
    category: "Vegetables",
    avoid: false,
    measurement: "1 tablespoon",
    notes: "",
  },
  {
    name: "Wombok",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Yam",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Yellow Capsicum",
    category: "Vegetables",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Zucchini",
    category: "Vegetables",
    avoid: false,
    measurement: "< ½ cup",
    notes: "",
  },
  {
    name: "Asparagus",
    category: "Vegetables",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Bitter Melon",
    category: "Vegetables",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Brown Onion",
    category: "Vegetables",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Cauliflower",
    category: "Vegetables",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Fresh Peas",
    category: "Vegetables",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Frozen Peas",
    category: "Vegetables",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Garlic",
    category: "Vegetables",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Globe Artichoke",
    category: "Vegetables",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Jerusalem Artichoke",
    category: "Vegetables",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Karela",
    category: "Vegetables",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Leek",
    category: "Vegetables",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Mushrooms",
    category: "Vegetables",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Red Onion",
    category: "Vegetables",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Shallots",
    category: "Vegetables",
    avoid: true,
    measurement: "Green only",
    notes: "",
  },
  {
    name: "Spring Onion",
    category: "Vegetables",
    avoid: true,
    measurement: "White part only",
    notes: "",
  },
  {
    name: "White Onion",
    category: "Vegetables",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Avocado",
    category: "Fruit",
    avoid: false,
    measurement: "1 to 2 tablespoons",
    notes: "",
  },
  {
    name: "Banana",
    category: "Fruit",
    avoid: false,
    measurement: "Firm",
    notes: "",
  },
  {
    name: "Blueberries",
    category: "Fruit",
    avoid: false,
    measurement: "1/3 cup",
    notes: "",
  },
  {
    name: "Cantaloupe",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Rockmelon",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Honeydew",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Carambola",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Dragon Fruit",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Clementine",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Coconut (Fresh)",
    category: "Fruit",
    avoid: false,
    measurement: "Up to 1 cup",
    notes: "",
  },
  {
    name: "Coconut (Dessicated)",
    category: "Fruit",
    avoid: false,
    measurement: "½ cup",
    notes: "",
  },
  {
    name: "Cumquats",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Dates",
    category: "Fruit",
    avoid: false,
    measurement: "Dried/Fresh (limit 1)",
    notes: "",
  },
  {
    name: "Figs",
    category: "Fruit",
    avoid: false,
    measurement: "Dried/Fresh (limit 1)",
    notes: "",
  },
  {
    name: "Grapefruit",
    category: "Fruit",
    avoid: false,
    measurement: "Up to ½",
    notes: "",
  },
  {
    name: "Red Grapes",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Green Grapes",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Guava",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Jackfruit",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Kiwifruit",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Lemon",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  { name: "Lime", category: "Fruit", avoid: false, measurement: "", notes: "" },
  {
    name: "Mandarin",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "White Nectarine",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Orange",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Passionfruit",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Pineapple",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Pomegranate",
    category: "Fruit",
    avoid: false,
    measurement: "¼ cup",
    notes: "",
  },
  {
    name: "Prickly Pear",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Rambutan",
    category: "Fruit",
    avoid: false,
    measurement: "Up to 3",
    notes: "",
  },
  {
    name: "Raspberries",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Rhubarb",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Star Fruit",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Strawberries",
    category: "Fruit",
    avoid: false,
    measurement: "",
    notes: "",
  },
  { name: "Apple", category: "Fruit", avoid: true, measurement: "", notes: "" },
  {
    name: "Fresh Apricot",
    category: "Fruit",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Dried Apricot",
    category: "Fruit",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Blackberries",
    category: "Fruit",
    avoid: true,
    measurement: "Ripe",
    notes: "",
  },
  {
    name: "Boysenberries",
    category: "Fruit",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Cherries",
    category: "Fruit",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Custard Apple",
    category: "Fruit",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Feijoa",
    category: "Fruit",
    avoid: true,
    measurement: "",
    notes: "",
  },
  { name: "Mango", category: "Fruit", avoid: true, measurement: "", notes: "" },
  {
    name: "Nectarine",
    category: "Fruit",
    avoid: true,
    measurement: "",
    notes: "",
  },
  { name: "Peach", category: "Fruit", avoid: true, measurement: "", notes: "" },
  { name: "Pear", category: "Fruit", avoid: true, measurement: "", notes: "" },
  {
    name: "Persimmon",
    category: "Fruit",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Sugar Banana",
    category: "Fruit",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Tamarillo",
    category: "Fruit",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Watermelon",
    category: "Fruit",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Amaranth",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "¼ cup puffed, not flour",
    notes: "",
  },
  {
    name: "Arrowroot",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Bread",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "2 slices",
    notes: "",
  },
  {
    name: "Buckwheat",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Cacao Powder",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Carob",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "1 heaped teaspoon",
    notes: "",
  },
  {
    name: "Corn Flour",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Corn Starch",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Fruit-Free Cereals",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "FODMAP Certified Cereals",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Guar Gum",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Xanthan Gum",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Rolled Oats",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Fruit-Free Muesli",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Corn Cous-Cous",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Pasta",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "No soy or legume flours",
  },
  {
    name: "Polenta",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Quinoa",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Rice",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Rice Noodles",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Konjac",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Tapioca Flour",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Teff",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "FODMAP Certified Bread",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "2 slices",
    notes: "",
  },
  {
    name: "Gnocchi",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "80% Potato",
    notes: "",
  },
  {
    name: "Sourdough (Wheat/Spelt)",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "2 slices",
    notes: "",
  },
  {
    name: "Wheat Bread (Regular)",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "Up to 1 slice",
    notes: "",
  },
  {
    name: "Wheat Pasta",
    category: "Gluten Free Cereals & Grain",
    avoid: false,
    measurement: "Up to ½ cup",
    notes: "",
  },
  {
    name: "Besan Flour",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Chickpea Flour",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Coconut Flour",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Garbanzo Bean Flour",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Inulin",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Lupin",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Lupin Flour",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Soy Flour",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Muesli/Cereal with Honey",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Muesli/Cereal with Dried Fruit",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Muesli/Cereal with Fructose",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Fruit Juice Concentrate",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Pasta (Chickpea Flour)",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Pasta (Legume Flour)",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Pasta (Soy Flour)",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Cauliflower Rice",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Regular Breads",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Regular Biscuits",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Regular Cakes",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Barley",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Cous-Cous",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Rye",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Wheat-based Cereals",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Bran-based Cereals",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Wheat Pasta",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Semolina Pasta",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Spelt Pasta",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Egg Noodles",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Udon Noodles",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Ramen",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Instant Wheat Noodles",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Noodle Soups",
    category: "Gluten Free Cereals & Grain",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Cheese (Set/Firm)",
    category: "Milk Products",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Greek (Strained) Yoghurt",
    category: "Milk Products",
    avoid: false,
    measurement: "2 to 3 tablespoons",
    notes: "",
  },
  {
    name: "Lactose-Free Cow's Milk",
    category: "Milk Products",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Lactose-Free Cow's Milk Cream",
    category: "Milk Products",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Lactose-Free Cow's Milk Ice Cream",
    category: "Milk Products",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Lactose-Free Cow's Milk Yoghurt",
    category: "Milk Products",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Ricotta",
    category: "Milk Products",
    avoid: false,
    measurement: "2 tablespoons",
    notes: "",
  },
  {
    name: "Cream Cheese",
    category: "Milk Products",
    avoid: false,
    measurement: "2 tablespoons",
    notes: "",
  },
  {
    name: "Sour Cream",
    category: "Milk Products",
    avoid: false,
    measurement: "2 tablespoons",
    notes: "",
  },
  {
    name: "Cow's Milk",
    category: "Milk Products",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Regular Ice Cream",
    category: "Milk Products",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Regular Yoghurt",
    category: "Milk Products",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Regular Custard",
    category: "Milk Products",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Milk Kefir",
    category: "Milk Products",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Almond Milk",
    category: "Milk Alternatives",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Rice Milk",
    category: "Milk Alternatives",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Quinoa Milk",
    category: "Milk Alternatives",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Hemp Milk",
    category: "Milk Alternatives",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Coconut Milk (Tinned)",
    category: "Milk Alternatives",
    avoid: false,
    measurement: "½ cup",
    notes: "",
  },
  {
    name: "Coconut Cream",
    category: "Milk Alternatives",
    avoid: false,
    measurement: "½ cup",
    notes: "",
  },
  {
    name: "Pea Protein Milk",
    category: "Milk Alternatives",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Soy Milk",
    category: "Milk Alternatives",
    avoid: false,
    measurement: "",
    notes: "Must be made from soy protein.",
  },
  {
    name: "Soy Cheese",
    category: "Milk Alternatives",
    avoid: false,
    measurement: "",
    notes: "No onion or garlic.",
  },
  {
    name: "Oat Milk",
    category: "Milk Alternatives",
    avoid: true,
    measurement: "> ½ cup",
    notes: "",
  },
  {
    name: "Soy Milk",
    category: "Milk Alternatives",
    avoid: true,
    measurement: "",
    notes: "Must be made from whole soy beans.",
  },
  {
    name: "White Sugar",
    category: "Sweeteners",
    avoid: false,
    measurement: "1 tablespoon",
    notes: "",
  },
  {
    name: "Castor Sugar",
    category: "Sweeteners",
    avoid: false,
    measurement: "1 tablespoon",
    notes: "",
  },
  {
    name: "Icing Sugar",
    category: "Sweeteners",
    avoid: false,
    measurement: "1 tablespoon",
    notes: "",
  },
  {
    name: "Brown Sugar",
    category: "Sweeteners",
    avoid: false,
    measurement: "1 tablespoon",
    notes: "",
  },
  {
    name: "Coconut Sugar",
    category: "Sweeteners",
    avoid: false,
    measurement: "1 tablespoon",
    notes: "",
  },
  {
    name: "Powdered Sugar",
    category: "Sweeteners",
    avoid: false,
    measurement: "1 tablespoon",
    notes: "",
  },
  {
    name: "Glucose",
    category: "Sweeteners",
    avoid: false,
    measurement: "1 tablespoon",
    notes: "",
  },
  {
    name: "Glucose Syrup",
    category: "Sweeteners",
    avoid: false,
    measurement: "1 tablespoon",
    notes: "",
  },
  {
    name: "Dextrose",
    category: "Sweeteners",
    avoid: false,
    measurement: "1 tablespoon",
    notes: "",
  },
  {
    name: "Golden Syrup",
    category: "Sweeteners",
    avoid: false,
    measurement: "½ tablespoons",
    notes: "",
  },
  {
    name: "Invert Sugar",
    category: "Sweeteners",
    avoid: false,
    measurement: "1 tablespoon",
    notes: "",
  },
  {
    name: "Maple Syrup",
    category: "Sweeteners",
    avoid: false,
    measurement: "1 tablespoon",
    notes: "",
  },
  {
    name: "Molasses",
    category: "Sweeteners",
    avoid: false,
    measurement: "½ tablespoons",
    notes: "",
  },
  {
    name: "Rice Malt Syrup",
    category: "Sweeteners",
    avoid: false,
    measurement: "1 tablespoon",
    notes: "",
  },
  {
    name: "Stevia",
    category: "Sweeteners",
    avoid: false,
    measurement: "1 tablespoon",
    notes: "",
  },
  {
    name: "Agave",
    category: "Sweeteners",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Honeydew",
    category: "Sweeteners",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Isomalt",
    category: "Sweeteners",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Mannitol",
    category: "Sweeteners",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Maltilol",
    category: "Sweeteners",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Sorbitol",
    category: "Sweeteners",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Treacle",
    category: "Sweeteners",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Xylitol",
    category: "Sweeteners",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Almonds",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "1 handful",
    notes: "",
  },
  {
    name: "Brazil Nuts",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "1 handful",
    notes: "",
  },
  {
    name: "Hazelnuts",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "1 handful",
    notes: "",
  },
  {
    name: "Mixed Nuts",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "1 handful",
    notes: "",
  },
  {
    name: "Peanuts",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "1 handful",
    notes: "",
  },
  {
    name: "Pecans",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "1 handful",
    notes: "",
  },
  {
    name: "Pine Nuts",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "1 handful",
    notes: "",
  },
  {
    name: "Walnuts",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "1 handful",
    notes: "",
  },
  {
    name: "Sesame Seeds",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "1 handful",
    notes: "",
  },
  {
    name: "Sunflower Seeds",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "1 handful",
    notes: "",
  },
  {
    name: "Linseeds",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "1 handful",
    notes: "",
  },
  {
    name: "Poppy Seeds",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "1 handful",
    notes: "",
  },
  {
    name: "Pepitas",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "1 handful",
    notes: "",
  },
  {
    name: "Canned Butter Beans",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "¼ cup",
    notes: "",
  },
  {
    name: "Canned Chick Peas",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "¼ cup",
    notes: "",
  },
  {
    name: "Canned Lentils",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "¼ cup",
    notes: "",
  },
  {
    name: "Lima Beans",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "¼ cup",
    notes: "",
  },
  {
    name: "Chia Seeds",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "1 tablespoon",
    notes: "",
  },
  {
    name: "Quorn",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "¼ cup",
    notes: "No onion or garlic.",
  },
  {
    name: "Tempeh",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "¼ cup",
    notes: "No onion or garlic.",
  },
  {
    name: "Tofu (Firm)",
    category: "Nuts, Seeds, & Legumes",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Cashews",
    category: "Nuts, Seeds, & Legumes",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Pistachio Nuts",
    category: "Nuts, Seeds, & Legumes",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Baked Beans",
    category: "Nuts, Seeds, & Legumes",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Black Beans",
    category: "Nuts, Seeds, & Legumes",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Borlotti Beans",
    category: "Nuts, Seeds, & Legumes",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Broad Beans",
    category: "Nuts, Seeds, & Legumes",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Cannellini Beans",
    category: "Nuts, Seeds, & Legumes",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Fava Beans",
    category: "Nuts, Seeds, & Legumes",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Four Bean Mix",
    category: "Nuts, Seeds, & Legumes",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Garbanzo Beans",
    category: "Nuts, Seeds, & Legumes",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Haricot Beans",
    category: "Nuts, Seeds, & Legumes",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Navy Beans",
    category: "Nuts, Seeds, & Legumes",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Soy Beans",
    category: "Nuts, Seeds, & Legumes",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Tofu (Silken)",
    category: "Nuts, Seeds, & Legumes",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Eggs",
    category: "Meat & Alternatives",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Chicken (Fresh cuts/Minced/Ground)",
    category: "Meat & Alternatives",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Fish (Fresh cuts/Minced/Ground)",
    category: "Meat & Alternatives",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Tinned Fish",
    category: "Meat & Alternatives",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Plain Grilled Fish",
    category: "Meat & Alternatives",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Most Bacon/Ham/Salami",
    category: "Meat & Alternatives",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Meat Products",
    category: "Meat & Alternatives",
    avoid: false,
    measurement: "",
    notes: "No onion or garlic.",
  },
  {
    name: "GF Battered/Bread-Crumbed Products",
    category: "Meat & Alternatives",
    avoid: false,
    measurement: "",
    notes: "No onion or garlic.",
  },
  {
    name: "Firm Tofu",
    category: "Meat & Alternatives",
    avoid: false,
    measurement: "",
    notes: "Check flavours and spices in the ingredients.",
  },
  {
    name: "Smoked Trout",
    category: "Meat & Alternatives",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Smoked Salmon",
    category: "Meat & Alternatives",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Sausages containing Onion/Garlic Powder",
    category: "Meat & Alternatives",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Most crumbed or battered meat",
    category: "Meat & Alternatives",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Most crumbed or battered chicken",
    category: "Meat & Alternatives",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Most crumbed or battered fish",
    category: "Meat & Alternatives",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Most Vegetarian Burgers/Falafel",
    category: "Meat & Alternatives",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Dark Chocolate",
    category: "Snack Foods & Confectionery",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Most Jelly Beans/Lollies",
    category: "Snack Foods & Confectionery",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Fruit-Free Muesli Bars",
    category: "Snack Foods & Confectionery",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Jelly",
    category: "Snack Foods & Confectionery",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Pretzels (Regular)",
    category: "Snack Foods & Confectionery",
    avoid: false,
    measurement: "½ cup",
    notes: "",
  },
  {
    name: "Plain Hot Chips",
    category: "Snack Foods & Confectionery",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Plain Salted Potato Chips",
    category: "Snack Foods & Confectionery",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Popcorn",
    category: "Snack Foods & Confectionery",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Corn Thins",
    category: "Snack Foods & Confectionery",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Corn Chips",
    category: "Snack Foods & Confectionery",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Rice Cakes",
    category: "Snack Foods & Confectionery",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Crackers",
    category: "Snack Foods & Confectionery",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Cruskits",
    category: "Snack Foods & Confectionery",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Sweet & Plain Biscuits/Cookies",
    category: "Snack Foods & Confectionery",
    avoid: false,
    measurement: "2 pieces",
    notes: "",
  },
  {
    name: "Milk Chocolate",
    category: "Snack Foods & Confectionery",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "White Chocolate",
    category: "Snack Foods & Confectionery",
    avoid: true,
    measurement: "> 2 squares",
    notes: "",
  },
  {
    name: "Cup-a-Soup",
    category: "Snack Foods & Confectionery",
    avoid: true,
    measurement: "",
    notes: "No onion or garlic.",
  },
  {
    name: "Instant Noodles",
    category: "Snack Foods & Confectionery",
    avoid: true,
    measurement: "",
    notes: "No onion or garlic.",
  },
  {
    name: "Chips/Crackers",
    category: "Snack Foods & Confectionery",
    avoid: true,
    measurement: "",
    notes: "No onion or garlic.",
  },
  {
    name: "Almond Butter",
    category: "Condiments",
    avoid: false,
    measurement: "1 tablespoon",
    notes: "",
  },
  {
    name: "Eggplant Dip",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "No onion or garlic.",
  },
  {
    name: "Fish Sauce",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Herbs & Spices",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "Check for no onion or garlic in ingredients.",
  },
  {
    name: "Strawberry Jam",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Raspberry Jam",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Marmalade",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Vegemite",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Mayonnaise",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Mint Jelly",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Miso Paste",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Mustard",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Oyster Sauce",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Peanut Butter",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Remoulade",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Shrimp Paste",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Spirulina",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Soy Sauce",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Sweet and Sour Sauce",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "No garlic.",
  },
  {
    name: "Tomato & BBQ Sauce",
    category: "Condiments",
    avoid: false,
    measurement: "2 tablespoons",
    notes: "",
  },
  {
    name: "Worcestershire Sauce",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Vanilla Essence",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Vinegar",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Mirin",
    category: "Condiments",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Gravy Mix",
    category: "Condiments",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Marinades",
    category: "Condiments",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Pasta Sauce",
    category: "Condiments",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Curry Paste",
    category: "Condiments",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Honey",
    category: "Condiments",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Hummus",
    category: "Condiments",
    avoid: true,
    measurement: "",
    notes: "> 1 tablespoon",
  },
  {
    name: "Seasoning Mixes",
    category: "Condiments",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Relish and Chutney",
    category: "Condiments",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Tahini",
    category: "Condiments",
    avoid: true,
    measurement: "",
    notes: "> 1 tablespoon",
  },
  {
    name: "Cranberry Juice",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "1 cup",
  },
  {
    name: "Tomato Juice",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "1 cup",
  },
  {
    name: "Lime Juice",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "1 cup",
  },
  {
    name: "Lemon Juice",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "1 cup",
  },
  {
    name: "Spirulina Juice",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "1 cup",
  },
  {
    name: "Orange Juice (Fresh)",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "½ cup",
  },
  {
    name: "Coffee",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Black Tea",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Dandelion Tea (Weak)",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Peppermint Tea",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Green Tea",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Rooibos Tea",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Beer",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Whiskey",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "",
  },
  { name: "Gin", category: "Drinks", avoid: false, measurement: "", notes: "" },
  {
    name: "Vodka",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Champagne",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Red Wine",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "White Wine",
    category: "Drinks",
    avoid: false,
    measurement: "",
    notes: "",
  },
  {
    name: "Coconut Water",
    category: "Drinks",
    avoid: true,
    measurement: "",
    notes: "> ½ cup",
  },
  {
    name: "Apple Juice",
    category: "Drinks",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Mango Juice",
    category: "Drinks",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Pear Juice",
    category: "Drinks",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Kombucha",
    category: "Drinks",
    avoid: true,
    measurement: "",
    notes: "> ½ cup",
  },
  {
    name: "Milk Drinks",
    category: "Drinks",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Pomegranate Juice",
    category: "Drinks",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Chamomile Tea",
    category: "Drinks",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Dandelion Tea (Strong)",
    category: "Drinks",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Fennel Tea",
    category: "Drinks",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Oolong Tea",
    category: "Drinks",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Chai Tea (Powders)",
    category: "Drinks",
    avoid: true,
    measurement: "",
    notes: "",
  },
  { name: "Rum", category: "Drinks", avoid: true, measurement: "", notes: "" },
  {
    name: "Dessert Wine",
    category: "Drinks",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Apple Cider",
    category: "Drinks",
    avoid: true,
    measurement: "",
    notes: "",
  },
  {
    name: "Pear Cider",
    category: "Drinks",
    avoid: true,
    measurement: "",
    notes: "",
  },
];
